
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS ORDER_DETAIL;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ORDINE;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE IF NOT EXISTS address (
  id INT NOT NULL AUTO_INCREMENT,
  country VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  county VARCHAR(100) NOT NULL,
  street_address VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS product_category (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS supplier (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE IF NOT EXISTS customer (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE IF NOT EXISTS location (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  address_id INT NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE IF NOT EXISTS product (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  price DECIMAL NOT NULL,
  weight DOUBLE NOT NULL,
  product_category_id INTEGER NOT NULL,
  supplier_id INTEGER NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS stock (
  product_id INT NOT NULL,
  location_id INT NOT NULL,
  quantity INT,
  );
  
CREATE TABLE IF NOT EXISTS order_detail (
  id INT NOT NULL AUTO_INCREMENT,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE IF NOT EXISTS ordine (
  id INT NOT NULL AUTO_INCREMENT,
  location_id INT NOT NULL,
  customer_id INT NOT NULL,
  address_id INT NOT NULL, 
  PRIMARY KEY (id));
  